// web-ui/client/src/components/layout/sidebar.tsx
import { Link, useLocation } from "wouter";
import { 
  Home, 
  Wallet, 
  TrendingUp, 
  Bot, 
  Target, 
  BarChart3, 
  Settings,
  LogOut,
  Activity
} from "lucide-react";
import { cn } from "@/lib/utils";

const navigation = [
  { name: "Dashboard", href: "/", icon: Home },
  { name: "Portfolio", href: "/portfolio", icon: Wallet },
  { name: "Trading", href: "/trading", icon: TrendingUp },
  { name: "Algorithms", href: "/algorithms", icon: Bot },
  { name: "Strategies", href: "/strategies", icon: Target },
  { name: "Analytics", href: "/analytics", icon: BarChart3 },
  { name: "Settings", href: "/settings", icon: Settings },
];

export function Sidebar() {
  const [location] = useLocation();

  return (
    <aside className="w-64 sidebar-nav flex-shrink-0 flex flex-col">
      <div className="p-6">
        <div className="flex items-center space-x-3 mb-8">
          <div className="w-8 h-8 bg-carbon-blue rounded flex items-center justify-center">
            <Activity className="text-white w-4 h-4" />
          </div>
          <h1 className="text-xl font-semibold text-white">TradePro</h1>
        </div>
        
        <nav className="space-y-2">
          {navigation.map((item) => {
            const Icon = item.icon;
            const isActive = location === item.href;
            
            return (
              <Link key={item.name} href={item.href}>
                <a
                  className={cn(
                    "flex items-center space-x-3 px-3 py-2 rounded-lg transition-colors",
                    isActive ? "nav-item-active" : "nav-item"
                  )}
                >
                  <Icon className="w-4 h-4" />
                  <span>{item.name}</span>
                </a>
              </Link>
            );
          })}
        </nav>
      </div>

      <div className="mt-auto p-6 border-t border-[var(--carbon-gray-80)]">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 bg-carbon-blue rounded-full flex items-center justify-center">
            <span className="text-white font-medium">JD</span>
          </div>
          <div className="flex-1">
            <p className="font-medium text-white">John Doe</p>
            <p className="text-sm text-gray-400">Portfolio Manager</p>
          </div>
          <button className="text-gray-400 hover:text-white transition-colors">
            <LogOut className="w-4 h-4" />
          </button>
        </div>
      </div>
    </aside>
  );
}

// svelte-web-ui/src/lib/components/layout/Sidebar.svelte
<script>
    let activePage = "Trading";
  </script>
  
  <aside class="w-56 h-full bg-[#1E1E2D] text-white flex flex-col">
    <div class="text-2xl font-bold px-4 py-6 border-b border-gray-700">
      <div class="flex items-center space-x-2">
        <span class="bg-blue-600 px-2 py-1 rounded">\u25B2</span>
        <span>TradePro</span>
      </div>
    </div>
  
    <nav class="flex-1 px-4 py-4 space-y-2 text-sm">
      <div class="cursor-pointer px-3 py-2 rounded hover:bg-gray-700" class:bg-blue-700={activePage === 'Dashboard'}>Dashboard</div>
      <div class="cursor-pointer px-3 py-2 rounded hover:bg-gray-700" class:bg-blue-700={activePage === 'Portfolio'}>Portfolio</div>
      <div class="cursor-pointer px-3 py-2 rounded bg-blue-700">Trading</div>
      <div class="cursor-pointer px-3 py-2 rounded hover:bg-gray-700">Algorithms</div>
      <div class="cursor-pointer px-3 py-2 rounded hover:bg-gray-700">Strategies</div>
      <div class="cursor-pointer px-3 py-2 rounded hover:bg-gray-700">Analytics</div>
      <div class="cursor-pointer px-3 py-2 rounded hover:bg-gray-700">Settings</div>
    </nav>
  </aside>
  
  <style>
    aside div.active {
      background-color: #2563EB; /* Tailwind blue-600 */
    }
  </style>
